name:          Aten Coding Standards
description:   HTML and SCSS Development Standards.
url:           https://github.com/pixelwhip/code-guide

markdown:      rdiscount
permalink:     pretty
highlighter:   pygments
